version: '3'

includes:
  server: 
    taskfile: ./server/Taskfile.yml
    dir: ./server

  web: 
    taskfile: ./web/Taskfile.yml
    dir: ./web

dotenv: ['api/.env', 'web/.env']

tasks:
  test:
    desc: Runs all tests both api and web
    cmds:
      - task: server:test
      - task: web:test
  
  reset:
    cmds:
      - task: server:reset.hard
      - task: web:reset


  setup:
    cmds:
      - task: server:setup
      - task: web:setup