version: '3'

includes:
  api: 
    taskfile: ./api/Taskfile.yml
    dir: ./api

  web: 
    taskfile: ./web/Taskfile.yml
    dir: ./web

dotenv: ['api/.env', 'web/.env']

tasks:
  test:
    desc: Runs all tests both api and web
    cmds:
      - task: api:test
      - task: web:test
  
  reset:
    cmds:
      - task: api:reset.hard
      - task: web:reset


  setup:
    cmds:
      - task: api:setup
      - task: web:setup