version: "3.8"

services:
  host:
    image: qoomon/docker-host:latest
    cap_add: ["NET_ADMIN", "NET_RAW"]
    mem_limit: 8M
    restart: on-failure

  rtmp:
    build:
      dockerfile: rtmp.dockerfile
      context: config
    ports:
      - 1935:1935
      - 8080:8080
    volumes:
      - ./tmp/rtmp:/tmp/rtmp
      - ./scripts/thumbnail.sh:/usr/local/bin/thumbnail.sh
      - ./config/nginx.conf:/etc/nginx/nginx.conf

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - 5672
      - 15671:15672

  db:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@suum.app
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5431:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    links:
      - "db:pgsql-server"

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    volumes:
      - bucket:/data
    entrypoint: minio server /data

volumes:
  bucket:
  database:
  pgadmin:
