version: "3"

tasks:
  compose.up: docker compose up -d
  compose.pause: docker compose pause
  compose.down: docker compose down -v
  compose.unpause: docker compose unpause

  up:
    desc: runs compose and setups project
    deps: [compose.up]
    cmds:
      - rails db:setup

  reset:
    desc: resets project config and services
    cmds:
      - task: down
      - task: up

  down:
    desc: wipes up services and tmp
    cmds:
      - rails db:drop
      - rails tmp:clear
      - task: compose.down

  seed:
    desc: adds data for development
    cmds:
      - rails db:seed

  bundle.install: bundle install

  migrate:
    desc: runs migrations
    cmds:
      - rails db:migrate

  routes:
    desc: shows routes for project
    cmds:
      - rails routes

  server:
    deps: [up]
    cmds:
      - rails server

  test:
    cmds:
      - rails spec

  test.watch:
    cmds:
      - bundle exec guard
