version: '3'

tasks:
  server:
    cmd: npm start

  clean:
    cmd: rm -rf ./node_modules

  test:
    desc: Runs tests
    cmds:
      - npm test --inspect-brk --runInBand --coverage false

  test.watch:
    desc: Runs tests in watch mode
    cmds:
      - npm run test.watch --inspect-brk --runInBand --coverage false