version: '3'

tasks:
  server:
    cmd: npm start

  setup:
    cmd: npm install

  build:
    cmd: npm run build

  reset:
    cmds: 
      - task: clean
      - task: setup

  clean:
    cmd: rm -rf ./node_modules

  test:
    desc: Runs tests
    cmds:
      - npm test --inspect-brk --runInBand --coverage false

  test.watch:
    desc: Runs tests in watch mode
    cmds:
      - npm run test.watch --inspect-brk --runInBand --coverage false

  npm.install:
    desc: Set variable PACKAGE_NAME to install a npm package like `npm install --save $PACKAGE_NAME`
    cmds:
      - npm install --save {{.PACKAGE_NAME}}

  npm.install.dev:
    desc: Set variable PACKAGE_NAME to install a npm package like `npm install --save-dev $PACKAGE_NAME`
    cmds:
      - npm install --save-dev {{.PACKAGE_NAME}}

  npm.uninstall:
    desc: Set variable PACKAGE_NAME to uninstall a npm package like `npm uninstall -S $PACKAGE_NAME`
    cmds:
      - npm uninstall -S {{.PACKAGE_NAME}}

      